### PR TITLE
✨ feat(app): Added real-time clear function

### PR DESCRIPTION
**Pull request by junddao**
- change eraser color from white to transparent
- I tested all feature of example like undo or redo (Previous my PR make mess up historical data. so I reset historical data base on currentIndex.)

@xSILENCEx

### CODE REVIEW

**Comment by AlexV525** [comment]
Please respect the CODEOWNERS of the repo and do not randomly ping unrelevant people until members cc others. :)

**Comment by junddao** [comment]
> Please respect the CODEOWNERS of the repo and do not randomly ping unrelevant people until members cc others. :)

We apologize for any inconvenience. (_ _) 
I'll be careful.

@AlexV525

**Comment by junddao** [comment]
@xSILENCEx

could you review this? 
If can't merge on master branch, I will use my repository that fork this.

**Comment by xSILENCEx** [comment]
Real-time eraser has been added

**Pull request closed without merging**
